
Assignment1:
1. Generate an np array of (a) vector of 50 lengths (b)  two dimensions of shape 4x5 uniformly distributed between 0 and 1.
2. Split the two dimensions array in 1 above into three arrays taking the first two rows, follow by the next two rows and put the remaining row into another variable. 
3. Split the vector array in 1 above into three arrays by taking the first 15, follow by the next 15 and putting the remaining into another variable. 
4. Create a 4x5 array (a)  using manual method (b)  using randomly generated values between 0 and 1(c) using array of ones.



In [95]:
import numpy as np

In [110]:
#1. Generate an np array of (a) vector of 50 lengths

d=np.arange(50)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [114]:
#(b)  two dimensions of shape 4x5 uniformly distributed between 0 and 1.

a=np.random.random((4,5))
a

array([[0.43133388, 0.91466546, 0.32883241, 0.6556093 , 0.12389201],
       [0.07854297, 0.3668159 , 0.79544765, 0.81442461, 0.40140951],
       [0.77819398, 0.28368249, 0.2431889 , 0.26653936, 0.15624727],
       [0.99560305, 0.06120314, 0.49880379, 0.70923664, 0.42902514]])

In [116]:
#To check the dimension pf an array

a.ndim

2

In [101]:
# 2. Split the two dimensions array in 1 above into three arrays taking the first two rows, 
#follow by the next two rows and put the remaining row into another variable.


first, second,third = np.vsplit(a, [2,4])
print("the first split\n",first)
print("the second split\n",second)
print("the third split\n",third)

the first split
 [[0.60663521 0.40551905 0.16993336 0.99207707 0.16193968]
 [0.10710127 0.28243463 0.5996992  0.50498954 0.03042404]]
the second split
 [[0.72230466 0.40520586 0.78856606 0.01252003 0.79727643]
 [0.43340771 0.22689728 0.17581207 0.58893696 0.09001501]]
the third split
 []


In [91]:
#3. Split the vector array in 1 above into three arrays by taking the first 15, 
#   follow by the next 15 and putting the remaining into another variable.

x1, x2, x3 = np.split(d, (15,30))
print(x1,x2,x3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29] [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [92]:
# 4. Create a 4x5 array (a)  using manual method

np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[17,19,20,21,22]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [17, 19, 20, 21, 22]])

In [107]:
#(b)  using randomly generated values between 0 and 1

np.random.randint(0,1,(4,5) )

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [94]:
#(c) using array of ones.

np.ones((4,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Assignment2:
#use us_births data to compute the following using np:
    #extract the year, gender and births column from the data
    #compute the aggregation of sum of total birth, sum of female birth and sum of male birth, mean and median
    #compute the maximum births and minimum births
    #indicate the gender with minimum birth and maximum birth
    #indicate the year with minimum birth and maximum birth

In [62]:
import numpy as np

In [63]:
import pandas as pd
us_births = pd.read_csv('C:\\Users\\AMOZ\\Documents\\data science materials\\Datasets\\us_births.csv')
us_births

year  month  day gender  births
0      1969      1  1.0      F    4046
1      1969      1  1.0      M    4440
2      1969      1  2.0      F    4454
3      1969      1  2.0      M    4548
4      1969      1  3.0      F    4548
...     ...    ...  ...    ...     ...
15542  2008     10  NaN      M  183219
15543  2008     11  NaN      F  158939
15544  2008     11  NaN      M  165468
15545  2008     12  NaN      F  173215
15546  2008     12  NaN      M  181235

[15547 rows x 5 columns]

In [39]:
us_year = np.array(us_births['year'])
print("us year\n",us_year,"\n")

us year
 [1969 1969 1969 ... 2008 2008 2008] 



In [64]:
 #extract the year, gender and births column from the data

us_year = np.array(us_births['year'])
us_gender = np.array(us_births['gender'])
us_birth = np.array(us_births['births'])
print("us year\n",us_year,"\n")
print("us gender\n",us_gender,"\n")
print("us births\n",us_birth)

us year
 [1969 1969 1969 ... 2008 2008 2008] 

us gender
 ['F' 'M' 'F' ... 'M' 'F' 'M'] 

us births
 [  4046   4440   4454 ... 165468 173215 181235]


In [70]:
#compute the aggregation of sum of total birth, sum of female birth and sum of male birth, mean and median


print("us total births sum: ", np.sum(us_birth))
print("us total births mean: ", np.mean(us_birth))
print("us total births median: ", np.median(us_birth))

us total births sum:  151774378
us total births mean:  9762.293561458802
us total births median:  4814.0


In [84]:
#compute the aggregation of sum of female birth and sum of male birth,
x= us_birth[0::2].sum()
print('aggregation of sum of female birth:',  x)

aggregation of sum of female birth: 76768938


In [85]:
y = us_birth[1::2].sum()
print('aggregation of sum of Male birth:',  y)

aggregation of sum of Male birth: 75005440


In [50]:
#compute the maximum births and minimum births

print("minimum births:   ", us_birth.argmin())
print("maximum births:   ", us_birth.argmax())

minimum births:    4715
maximum births:    15514


In [48]:
 #indicate the gender with minimum birth and maximum birth
    

a = us_gender[us_birth.argmax()]
b = us_gender[us_birth.argmin()]
print("gender with maximum birth\n",a)
print("gender with minimum birth\n", b)


gender with maximum birth
 M
gender with minimum birth
 F


In [53]:
#indicate the year with minimum birth and maximum birth

c = us_year[us_birth.argmax()]
d = us_year[us_birth.argmin()]
print("year with maximum birth\n",c)
print("year with minimum birth\n", d)

year with maximum birth
 2007
year with minimum birth
 1975
